<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite.Core" />
    <PackageReference Include="SQLite3MC.PCLRaw.bundle" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../DotOrbit.Core/DotOrbit.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="DotOrbit.Storage.Sqlite.Tests" />
  </ItemGroup>
</Project>
