<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite.Core" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/DotOrbit.Core/DotOrbit.Core.csproj" />
    <ProjectReference Include="../../src/DotOrbit.Storage.Sqlite/DotOrbit.Storage.Sqlite.csproj" />
  </ItemGroup>
</Project>
