<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>dot-orbit</AssemblyName>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <RuntimeIdentifiers>win-x64;linux-x64;osx-x64;osx-arm64</RuntimeIdentifiers>
  </PropertyGroup>
  <PropertyGroup Condition="'$(DotOrbitPackage)' == 'true'">
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../DotOrbit.Core/DotOrbit.Core.csproj" />
    <ProjectReference Include="../DotOrbit.Markdown/DotOrbit.Markdown.csproj" />
    <ProjectReference Include="../DotOrbit.Storage.Sqlite/DotOrbit.Storage.Sqlite.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="DotOrbit.Desktop.Tests" />
  </ItemGroup>
</Project>
